version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/work/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command: celery -A remote worker -l INFO
    volumes:
      - .:/usr/src/work/
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
  redis:
    image: "redis:alpine"
