# Generated by Django 4.0.1 on 2022-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('salary', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('profile_url', models.URLField(null=True)),
            ],
        ),
    ]
