# Generated by Django 4.0.1 on 2022-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
