# Generated by Django 4.0.2 on 2022-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
