# Generated by Django 4.0.5 on 2022-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_listing_profile_image_listing_application_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
