# Generated by Django 4.0.5 on 2022-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_listing_created_listing_failed_listing_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
